import Head from "next/head";
import SectionCharacters from "../components/Characters/SectionCharacters";
import TopPage from "../components/Common/TopPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lista Personagens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopPage title="Personagens"></TopPage>
      <SectionCharacters></SectionCharacters>
    </div>
  );
}
