import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [personagens, setPersonagens] = useState([])

  useEffect(async() => {
    var myHeaders = new Headers({
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Requested-With',
    });
 
    var myInit = { 
      'method': 'GET', 
      'headers': myHeaders,
      'Referrer-Policy': 'strict-origin-when-cross-origin',
      'cache-control': 'no-cache'
    };
    const response = await fetch('https://comicvine.gamespot.com/api/characters/?api_key=71b34195d29fedbe8f04f17cb304f9689187aa1c&format=json', myInit)
    const data = await response

    console.log(response)

    setPersonagens(data)
  }, [])    

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
